apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordcount
  labels:
    app.kubernetes.io/name: wordcount
    app.kubernetes.io/component: server
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/name: wordcount
      app.kubernetes.io/component: server
  template:
    metadata:
      labels:
        app.kubernetes.io/name: wordcount
        app.kubernetes.io/component: server
    spec:
      containers:
        - name: wordcount
          image: pcjun97/wordcount
          command:
            - "/app/wordcount"
            - "-s"
            - "-i"
            - "-p"
            - "3000"
          ports:
            - containerPort: 3000
